import type { Lesson } from "./tier0";

export const TIER1_TITLE = "Tier 1 · First Tactics";

/**
 * Tier 1 — First Tactics. Eight structured lessons that each teach one
 * tactical idea and point at a matching puzzle theme for practice.
 * Original content; FENs are simple illustrative positions.
 */
export const TIER1_LESSONS: Lesson[] = [
  {
    id: "t1-piece-values",
    tier: 1,
    order: 1,
    title: "Piece Values and Trades",
    subtitle: "Know what each piece is worth",
    explanation:
      "Before you can win material you need to know what material is worth. A pawn is 1, knight and bishop 3, rook 5, and the queen 9. A 'good trade' means giving up less value than you get back. When the totals are equal it is an even trade; grabbing a rook for a bishop wins 'the exchange'.",
    keyPoints: [
      "Pawn 1, knight 3, bishop 3, rook 5, queen 9.",
      "Trade when you gain value or improve your position.",
      "Winning a rook for a minor piece is 'winning the exchange'.",
    ],
    quiz: {
      question: "You can take a rook but lose your bishop doing so. Is that a good trade?",
      choices: ["No, never trade", "Only if you are losing", "Yes — 5 for 3 wins material", "It is an even trade"],
      correctIndex: 2,
    },
    xpReward: 60,
    relatedPuzzleTheme: "undefended-capture",
    fen: "4k3/8/2n5/3q4/5r2/8/8/4K3 w - - 0 1",
    boardCaption: "Queen 9, rook 5, knight 3 — the queen is the prize.",
    guide: "queen",
    steps: [
      { type: "intro", guide: "queen", title: "What's it worth?", text: "Vera here. Before you can win material you must know its worth: pawn 1, knight and bishop 3, rook 5 — and me, the queen, a mighty 9." },
      { type: "board-demo", fen: "4k3/8/2n5/3q4/5r2/8/8/4K3 w - - 0 1", highlights: ["c6", "d5", "f4"], prompt: "Rank these three pieces by value.", caption: "Knight 3, rook 5, queen 9 — the queen is worth the most.", guide: "queen" },
      { type: "tap-piece", fen: "4k3/8/2n5/3q4/5r2/8/8/4K3 w - - 0 1", prompt: "Tap the most valuable piece on the board.", targets: ["d5"], successText: "The queen — nine points, the strongest piece.", hint: "Worth more than a rook or a knight.", guide: "queen" },
      { type: "multiple-choice", prompt: "You can take a rook but lose your bishop doing so. Is that a good trade?", choices: ["No, never trade", "Yes — 5 for 3 wins material", "Only if you are losing", "It is an even trade"], correctIndex: 1, successText: "Right — 5 for 3 wins the exchange.", guide: "queen" },
    ],
  },
  {
    id: "t1-hanging-pieces",
    tier: 1,
    order: 2,
    title: "Hanging Pieces",
    subtitle: "Take what is left undefended",
    explanation:
      "A hanging piece is one that is not defended by anything. If your opponent leaves a piece hanging, you can simply capture it for free. Always scan the board for undefended enemy pieces before you move — and make sure your own pieces are defended too.",
    keyPoints: [
      "A hanging piece has no defender.",
      "Capturing a hanging piece wins material for free.",
      "Check your own pieces are defended before moving.",
    ],
    quiz: {
      question: "What makes a piece 'hanging'?",
      choices: ["It is pinned", "It gives check", "It is on the edge", "It has no defender"],
      correctIndex: 3,
    },
    xpReward: 60,
    fen: "4k3/8/8/3b4/8/4N3/8/4K3 w - - 0 1",
    boardCaption: "The black bishop on d5 is undefended — Nxd5 wins it.",
    relatedPuzzleTheme: "hanging-piece",
    guide: "knight",
    steps: [
      {
        type: "intro",
        guide: "knight",
        title: "Free material",
        text: "I'm Gallop! A hanging piece has no defender. If your opponent leaves one, you just take it — for free.",
      },
      {
        type: "board-demo",
        fen: "4k3/8/8/3b4/8/4N3/8/4K3 w - - 0 1",
        highlights: ["d5"],
        prompt: "Scan for undefended enemy pieces.",
        caption: "Nothing guards the bishop on d5 — it's hanging.",
        guide: "knight",
      },
      {
        type: "make-move",
        fen: "4k3/8/8/3b4/8/4N3/8/4K3 w - - 0 1",
        correctUci: "e3d5",
        prompt: "Win the free bishop — move your knight to capture it.",
        successText: "Nxd5 — a whole piece for nothing!",
        failureText: "That's not the capture. Take the undefended bishop on d5.",
        hint: "Knight from e3 jumps to d5.",
        guide: "knight",
      },
      {
        type: "multiple-choice",
        prompt: "What makes a piece 'hanging'?",
        choices: ["It has no defender", "It is pinned", "It is on the edge", "It gives check"],
        correctIndex: 0,
        successText: "Right — no defender means free material.",
        guide: "knight",
      },
    ],
  },
  {
    id: "t1-forks",
    tier: 1,
    order: 3,
    title: "Forks",
    subtitle: "One piece, two targets",
    explanation:
      "A fork is a single move that attacks two or more enemy pieces at once. Knights are famous forkers because they hit squares no other piece can defend easily. When you fork the king and another piece, the opponent must save the king and you win the other piece.",
    keyPoints: [
      "A fork attacks two targets at the same time.",
      "Knight forks of king and queen are devastating.",
      "Look for forks whenever enemy pieces line up a knight-move apart.",
    ],
    quiz: {
      question: "Why is a knight fork on the king and queen so strong?",
      choices: [
        "It gives checkmate",
        "The king must move, so the queen is lost",
        "Knights cannot be captured",
        "It promotes a pawn",
      ],
      correctIndex: 1,
    },
    xpReward: 60,
    fen: "4k3/8/8/3q4/6N1/8/8/4K3 w - - 0 1",
    boardCaption: "Nf6+ forks the king on e8 and the queen on d5.",
    relatedPuzzleTheme: "fork",
    guide: "knight",
    steps: [
      {
        type: "intro",
        guide: "knight",
        title: "One move, two targets",
        text: "A fork attacks two pieces at once. Knights are the deadliest forkers — they hit squares nothing else can defend.",
      },
      {
        type: "board-demo",
        fen: "4k3/8/8/3q4/6N1/8/8/4K3 w - - 0 1",
        highlights: ["e8", "d5"],
        prompt: "The king and queen are a knight's-jump apart.",
        caption: "One square attacks both at once: f6.",
        guide: "knight",
      },
      {
        type: "make-move",
        fen: "4k3/8/8/3q4/6N1/8/8/4K3 w - - 0 1",
        correctUci: "g4f6",
        prompt: "Fork the king and queen — leap in with check!",
        successText: "Nf6+! The king must move and the queen drops.",
        failureText: "Find the square that checks the king AND hits the queen.",
        hint: "Knight to f6.",
        guide: "knight",
      },
      {
        type: "multiple-choice",
        prompt: "Why is a knight fork of king and queen so strong?",
        choices: [
          "Knights cannot be captured",
          "It is checkmate",
          "The king must move, so the queen is lost",
          "It promotes a pawn",
        ],
        correctIndex: 2,
        successText: "Exactly — the check wins the queen.",
        guide: "knight",
      },
    ],
  },
  {
    id: "t1-pins",
    tier: 1,
    order: 4,
    title: "Pins",
    subtitle: "Freeze a piece in place",
    explanation:
      "A pin is when a piece cannot move because doing so would expose a more valuable piece behind it. In an absolute pin the piece behind is the king, so the pinned piece is legally stuck. Pile more attackers onto a pinned piece — it cannot run away.",
    keyPoints: [
      "A pin holds a piece in front of a more valuable one.",
      "An absolute pin is against the king — the piece truly cannot move.",
      "Attack a pinned piece again to win it.",
    ],
    quiz: {
      question: "A knight is pinned to its king. What can you do?",
      choices: [
        "Nothing, pins are harmless",
        "Only give check",
        "The knight can still jump away",
        "Attack the knight again to win it",
      ],
      correctIndex: 3,
    },
    xpReward: 60,
    fen: "4k3/4n3/3P4/8/8/8/8/4R1K1 w - - 0 1",
    boardCaption: "The e7-knight is pinned by the rook — dxe7 wins it.",
    relatedPuzzleTheme: "pin",
    guide: "rook",
    steps: [
      { type: "intro", guide: "rook", title: "Frozen in place", text: "Bramble here. A pinned piece can't move — stepping aside would expose something more valuable behind it. So pile on and win it." },
      { type: "board-demo", fen: "4k3/4n3/3P4/8/8/8/8/4R1K1 w - - 0 1", highlights: ["e1", "e7", "e8"], prompt: "The rook stares down the e-file: knight, then king.", caption: "The e7 knight is pinned to its king — it legally cannot move.", guide: "rook" },
      { type: "make-move", fen: "4k3/4n3/3P4/8/8/8/8/4R1K1 w - - 0 1", correctUci: "d6e7", prompt: "The knight can't run. Win it — capture with your pawn!", successText: "dxe7! The pinned knight had no escape.", failureText: "Capture the pinned knight with your d6 pawn.", hint: "Pawn d6 takes e7.", guide: "rook" },
      { type: "multiple-choice", prompt: "A knight is pinned to its king. What can you do?", choices: ["Attack the knight again to win it", "Nothing, pins are harmless", "The knight can still jump away", "Only give check"], correctIndex: 0, successText: "Right — pile onto a pinned piece and win it.", guide: "rook" },
    ],
  },
  {
    id: "t1-skewers",
    tier: 1,
    order: 5,
    title: "Skewers",
    subtitle: "The pin, reversed",
    explanation:
      "A skewer is like a pin turned around: the more valuable piece is in front and is forced to move, exposing the piece behind it. Check the king along a line, the king steps aside, and you capture the rook or queen that was hiding behind it.",
    keyPoints: [
      "In a skewer the valuable piece is in front and must move.",
      "Rooks, bishops and queens deliver skewers along lines.",
      "Skewer the king to win the piece behind it.",
    ],
    quiz: {
      question: "How does a skewer differ from a pin?",
      choices: [
        "It only uses knights",
        "It never gives check",
        "The more valuable piece is in front and must move",
        "There is no difference",
      ],
      correctIndex: 2,
    },
    xpReward: 60,
    fen: "3q4/8/8/8/3k4/8/8/R5K1 w - - 0 1",
    boardCaption: "Rd1+ skewers the king to the queen behind it.",
    relatedPuzzleTheme: "skewer",
    guide: "queen",
    steps: [
      { type: "intro", guide: "queen", title: "The pin, reversed", text: "Vera here. A skewer hits the valuable piece in front. It must move — and you snap up whatever was hiding behind it." },
      { type: "board-demo", fen: "3q4/8/8/8/3k4/8/8/R5K1 w - - 0 1", highlights: ["d4", "d8"], prompt: "King in front, queen behind — both on the d-file.", caption: "Check the king and it must step aside, exposing the queen.", guide: "queen" },
      { type: "make-move", fen: "3q4/8/8/8/3k4/8/8/R5K1 w - - 0 1", correctUci: "a1d1", prompt: "Skewer the king to the queen — check down the d-file!", successText: "Rd1+! The king moves and the queen drops.", failureText: "Put your rook on the d-file with check.", hint: "Rook a1 to d1.", guide: "queen" },
      { type: "multiple-choice", prompt: "How does a skewer differ from a pin?", choices: ["It only uses knights", "The more valuable piece is in front and must move", "It never gives check", "There is no difference"], correctIndex: 1, successText: "Exactly — valuable piece in front, forced to move.", guide: "queen" },
    ],
  },
  {
    id: "t1-discovered-attacks",
    tier: 1,
    order: 6,
    title: "Discovered Attacks",
    subtitle: "Move one piece, unleash another",
    explanation:
      "A discovered attack happens when you move one piece out of the way and the piece behind it suddenly attacks. If the moving piece also gives check or makes a threat, the opponent cannot answer both — that is a discovered double threat, one of the most powerful tactics.",
    keyPoints: [
      "Moving a front piece reveals an attack from the piece behind.",
      "Discovered checks are especially strong — two threats at once.",
      "Look for your own pieces lined up behind a movable piece.",
    ],
    quiz: {
      question: "What powers a discovered attack?",
      choices: [
        "A pin",
        "Castling",
        "Promoting a pawn",
        "A piece moving aside to reveal another's attack",
      ],
      correctIndex: 3,
    },
    xpReward: 60,
    fen: "2q1k3/8/8/8/4N3/8/8/4R1K1 w - - 0 1",
    boardCaption: "Nd6+ is a discovered double check — then Nxc8 wins the queen.",
    relatedPuzzleTheme: "discovered-attack",
    guide: "knight",
    steps: [
      { type: "intro", guide: "knight", title: "Move one, unleash another", text: "Gallop! Slide one piece away and the piece behind it springs to life. Do both at once and the opponent can't answer everything." },
      { type: "board-demo", fen: "2q1k3/8/8/8/4N3/8/8/4R1K1 w - - 0 1", highlights: ["e1", "e4", "e8"], prompt: "The rook hides behind the knight on the e-file.", caption: "Jump the knight away and the rook's attack is revealed.", guide: "knight" },
      { type: "make-move", fen: "2q1k3/8/8/8/4N3/8/8/4R1K1 w - - 0 1", correctUci: "e4d6", prompt: "Leap the knight away with check — and discover the rook!", successText: "Nd6+! Double check — the king must move, then Nxc8 wins the queen.", failureText: "Find the knight jump that checks AND uncovers the rook.", hint: "Knight e4 to d6.", guide: "knight" },
      { type: "multiple-choice", prompt: "What powers a discovered attack?", choices: ["A piece moving aside to reveal another's attack", "Castling", "Promoting a pawn", "A pin"], correctIndex: 0, successText: "Right — one move, two attackers.", guide: "knight" },
    ],
  },
  {
    id: "t1-removing-the-defender",
    tier: 1,
    order: 7,
    title: "Removing the Defender",
    subtitle: "Take out the guard",
    explanation:
      "Sometimes a piece or a key square is only held up by a single defender. Capture or chase away that defender and the thing it was protecting falls. Always ask: what is defending the piece I want — and can I remove it?",
    keyPoints: [
      "Find the one piece holding a square or piece together.",
      "Capture or deflect that defender.",
      "What it was guarding now collapses.",
    ],
    quiz: {
      question: "A rook is the only piece guarding the back rank. What is the plan?",
      choices: [
        "Ignore it",
        "Offer a draw",
        "Remove or trade that rook, then mate",
        "Push a pawn",
      ],
      correctIndex: 2,
    },
    xpReward: 60,
    fen: "3r2k1/5ppp/8/8/8/8/8/3R2K1 w - - 0 1",
    boardCaption: "Rxd8# removes the lone defender and mates.",
    relatedPuzzleTheme: "remove-defender",
    guide: "rook",
    steps: [
      { type: "intro", guide: "rook", title: "Take out the guard", text: "Bramble again. One defender often holds everything together. Remove it and the prize it protected simply falls." },
      { type: "board-demo", fen: "3r2k1/5ppp/8/8/8/8/8/3R2K1 w - - 0 1", highlights: ["d8"], prompt: "What is the only thing guarding Black's back rank?", caption: "The d8 rook is the lone defender — trade it off.", guide: "rook" },
      { type: "make-move", fen: "3r2k1/5ppp/8/8/8/8/8/3R2K1 w - - 0 1", correctUci: "d1d8", prompt: "Remove the defender — capture the rook on d8!", successText: "Rxd8#! With the guard gone, it's mate.", failureText: "Capture the defending rook on d8.", hint: "Rook d1 takes d8.", guide: "rook" },
      { type: "multiple-choice", prompt: "A rook is the only piece guarding the back rank. What is the plan?", choices: ["Ignore it", "Remove or trade that rook, then mate", "Offer a draw", "Push a pawn"], correctIndex: 1, successText: "Remove the defender — then strike.", guide: "rook" },
    ],
  },
  {
    id: "t1-mate-in-one",
    tier: 1,
    order: 8,
    title: "Mate in One Patterns",
    subtitle: "Spot the finishing blow",
    explanation:
      "The goal of every tactic is checkmate. Train your eye to spot mate in one: a check the king cannot escape, block, or capture out of. Back-rank mates, supported queen mates, and corner mates are the patterns you will see again and again.",
    keyPoints: [
      "Mate in one is a check with no legal reply.",
      "Watch for trapped kings on the back rank.",
      "A supported queen next to the king is often mate.",
    ],
    quiz: {
      question: "What defines checkmate?",
      choices: [
        "The king is in the centre",
        "The queen is captured",
        "A pawn promotes",
        "The king is in check with no legal move",
      ],
      correctIndex: 3,
    },
    xpReward: 60,
    fen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1",
    boardCaption: "Ra8# — the king is trapped by its own pawns.",
    relatedPuzzleTheme: "mate-in-1",
    guide: "king",
    steps: [
      { type: "intro", guide: "king", title: "The finishing blow", text: "Cassius here. Every tactic aims at this moment: a check the king cannot escape, block, or capture. Find mate in one." },
      { type: "board-demo", fen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1", highlights: ["g8", "f7", "g7", "h7"], prompt: "Where can the black king run?", caption: "Boxed in by its own pawns — the back rank is the weakness.", guide: "king" },
      { type: "make-move", fen: "6k1/5ppp/8/8/8/8/8/R5K1 w - - 0 1", correctUci: "a1a8", prompt: "Deliver mate — rook to the back rank!", successText: "Ra8#! The king's own pawns seal its fate.", failureText: "Strike the 8th rank where the king is trapped.", hint: "Rook a1 all the way to a8.", guide: "king" },
      { type: "multiple-choice", prompt: "What defines checkmate?", choices: ["The king is in check with no legal move", "The queen is captured", "A pawn promotes", "The king is in the centre"], correctIndex: 0, successText: "In check with no escape — game over!", guide: "king" },
    ],
  },
];
