import type { Puzzle } from "./beginner";

/**
 * Engine-generated tactics (Sprint 25) — produced by scripts/genPuzzles.mts from
 * seeded random self-play, each a UNIQUE statically-verified mate-in-1 or clean
 * material win. Do not edit by hand; regenerate with `npm run genpuzzles`. The
 * engine soundness test (scripts/engineCheck.mts) re-verifies every entry.
 */
export const GENERATED_PUZZLES: Puzzle[] = [
  {
    id: "g03-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1020,
    fen: "2b4r/2p2ppp/r1k1p2n/1p6/5P1q/b1N5/P2PP1P1/RNBK1B1R w - - 0 19",
    sideToMove: "w",
    correctUci: "h1h4",
    answerSan: "Rxh4",
    explanation: "Rxh4 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 30,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g06-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1030,
    fen: "r2k1bnr/2p1p3/p3bp2/1p1p3p/Q7/N2P3q/PP1BPP2/R3KBR1 b Q - 1 20",
    sideToMove: "b",
    correctUci: "b5a4",
    answerSan: "bxa4",
    explanation: "bxa4 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 30,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g08-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1050,
    fen: "2bk3r/rp3pb1/4p3/pqppn2Q/P1N2KP1/2P1P1RP/1P1P4/RNB2B2 w - - 7 20",
    sideToMove: "w",
    correctUci: "a4b5",
    answerSan: "axb5",
    explanation: "axb5 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 31,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g25-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1080,
    fen: "rnb1kbnr/p1p1pp2/7p/1p4p1/P2P4/N5qP/BPPP1PP1/1RBQK2R w Kkq - 1 11",
    sideToMove: "w",
    correctUci: "f2g3",
    answerSan: "fxg3",
    explanation: "fxg3 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 32,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g23-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1090,
    fen: "rn1q1b1r/p1pQpp1p/5kp1/3p1b2/2P3n1/P6N/1P1PPPPP/R1BNKB1R w KQ - 4 13",
    sideToMove: "w",
    correctUci: "d7d8",
    answerSan: "Qxd8",
    explanation: "Qxd8 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 32,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g16-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1130,
    fen: "rnb1k2r/1p1p1p1p/2pb1np1/p3p2P/Nq6/1PPP1NP1/P2QPPB1/R1B1K1R1 w Qkq - 3 13",
    sideToMove: "w",
    correctUci: "c3b4",
    answerSan: "cxb4",
    explanation: "cxb4 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 33,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g20-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1130,
    fen: "1rbk1b1r/1pnpp1p1/5p1p/pqp3n1/PP3PP1/R1PPP2P/1B6/1NKQ1BNR w - - 5 16",
    sideToMove: "w",
    correctUci: "a4b5",
    answerSan: "axb5",
    explanation: "axb5 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 33,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g04-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1160,
    fen: "rn1qkb1r/3pp3/bpp2pNp/3P1n2/p5P1/N3Q3/PPP1P2P/R1B1KB1R b KQkq - 0 11",
    sideToMove: "b",
    correctUci: "f5e3",
    answerSan: "Nxe3",
    explanation: "Nxe3 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 34,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g01-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1180,
    fen: "1nbqk1nr/1pp1pp1p/r7/3p2N1/3b3P/Np2PQ2/P1P2PPR/R1BK1B2 b k - 1 11",
    sideToMove: "b",
    correctUci: "d4a1",
    answerSan: "Bxa1",
    explanation: "Bxa1 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 34,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g14-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1180,
    fen: "rnbk2nr/pQ1p3p/2p1ppP1/2b5/5P2/N1P5/PP1PP2P/R1B1KBNR w KQ - 0 11",
    sideToMove: "w",
    correctUci: "b7a8",
    answerSan: "Qxa8",
    explanation: "Qxa8 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 34,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g22-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1180,
    fen: "1nbqkbn1/1pp1p1p1/r4p2/3p1N2/Pp6/2Pr4/3PPPP1/RNBQKB1R w KQ - 0 11",
    sideToMove: "w",
    correctUci: "e2d3",
    answerSan: "exd3",
    explanation: "exd3 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 34,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g19-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1190,
    fen: "rnb4r/1p1k1p1p/2qp3b/p1p1pn1P/1P1P1P2/P1NQ2P1/R1P1K3/2B2BNR b - - 0 20",
    sideToMove: "b",
    correctUci: "c6h1",
    answerSan: "Qxh1",
    explanation: "Qxh1 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 34,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g10-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1200,
    fen: "rnbqkb1r/pp1ppp1p/8/1Pp3p1/8/N1PPB3/PQ2PnPP/R3KBNR b KQkq - 1 8",
    sideToMove: "b",
    correctUci: "f2h1",
    answerSan: "Nxh1",
    explanation: "Nxh1 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 35,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g18-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1200,
    fen: "r1b1k1nr/p1pp1p1p/Bpn1p3/2b5/N3P1pq/P2Q4/1PPP1PP1/R1B1K1NR b KQkq - 3 10",
    sideToMove: "b",
    correctUci: "h4h1",
    answerSan: "Qxh1",
    explanation: "Qxh1 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 35,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g11-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1210,
    fen: "1nbqkb1r/1pppppp1/4Bn2/p5Pp/r7/2P2N2/PP1PPP1P/RNBQ1RK1 w k - 2 8",
    sideToMove: "w",
    correctUci: "d1a4",
    answerSan: "Qxa4",
    explanation: "Qxa4 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 35,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g13-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1210,
    fen: "rn2kbnr/1p2pNp1/p6p/2p5/1P3PbP/2P4q/P2PP3/1RBQK1R1 b kq - 0 15",
    sideToMove: "b",
    correctUci: "e8f7",
    answerSan: "Kxf7",
    explanation: "Kxf7 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 35,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g12-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1230,
    fen: "rn2kbnr/1b2p1p1/p1p4p/1p1p2N1/Pq1PPP2/6P1/1BPNB1QP/4K2R b kq - 2 18",
    sideToMove: "b",
    correctUci: "b4b2",
    answerSan: "Qxb2",
    explanation: "Qxb2 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 35,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g17-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1230,
    fen: "2b1kbnr/1rpqp3/3p3p/P4pp1/P1NP1PP1/Rn2P3/1P4BP/1NB1K2R b K - 0 16",
    sideToMove: "b",
    correctUci: "b3c1",
    answerSan: "Nxc1",
    explanation: "Nxc1 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 35,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g09-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1240,
    fen: "rn1q1b1r/pbp2ppp/4k3/1QPp3n/P2P1p1P/8/1P2P1P1/RNB1KBNR w KQ d6 0 11",
    sideToMove: "w",
    correctUci: "b5b7",
    answerSan: "Qxb7",
    explanation: "Qxb7 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 36,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g24-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1240,
    fen: "2bqkbnr/r1pp1p1p/2n5/ppB1N3/1P2P3/N2P1B2/P1P2PPP/R2QK2R b KQk - 0 11",
    sideToMove: "b",
    correctUci: "c6e5",
    answerSan: "Nxe5",
    explanation: "Nxe5 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 36,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g26-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1240,
    fen: "r3kbnr/p3p2p/n1ppPpp1/q7/5Pb1/P5P1/1PPP3P/RNBQK1NR w KQkq - 1 10",
    sideToMove: "w",
    correctUci: "d1g4",
    answerSan: "Qxg4",
    explanation: "Qxg4 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 36,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g05-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1260,
    fen: "r1bqk2r/n2pp2p/1p1B2pb/p1p2pP1/1P3n1P/2PP3R/P3P3/RNQ1KBN1 b Qkq - 1 13",
    sideToMove: "b",
    correctUci: "e7d6",
    answerSan: "exd6",
    explanation: "exd6 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 36,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g21-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1260,
    fen: "rn1qkb1r/1p2p2p/p2p3n/2p5/3PPpp1/N1P2P1P/bP1Q2PR/R1B1KBN1 w Qkq - 0 11",
    sideToMove: "w",
    correctUci: "a1a2",
    answerSan: "Rxa2",
    explanation: "Rxa2 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 36,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g02-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1270,
    fen: "1nb1k3/2qp3r/rp4pn/p1p1ppbp/PN2P2P/1PP2P1R/1BQPK1P1/R4BN1 w - - 0 19",
    sideToMove: "w",
    correctUci: "h4g5",
    answerSan: "hxg5",
    explanation: "hxg5 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 36,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g07-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1270,
    fen: "r1bqk1nr/pppp1p1p/4p2b/n5p1/1PP4P/N4N2/P2PPPP1/R1BQKB1R w KQkq - 0 6",
    sideToMove: "w",
    correctUci: "b4a5",
    answerSan: "bxa5",
    explanation: "bxa5 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 36,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
  {
    id: "g15-undefended-capture",
    title: "Win the material",
    theme: "undefended-capture",
    rating: 1270,
    fen: "rnb1k2r/1p2nppp/1qp1p3/p2p3P/PP5R/b1N2P2/1RPPP1P1/2BQKBN1 b kq - 1 9",
    sideToMove: "b",
    correctUci: "b6g1",
    answerSan: "Qxg1",
    explanation: "Qxg1 wins material cleanly: the captured piece cannot be recovered.",
    xpReward: 36,
    categories: ["tactics"],
    hint: "Scan for an enemy piece you can take for free.",
  },
];
